export const ADMIN_NAV = [
  {
    href: '/admin',
    label: 'Dashboard',
    eyebrow: 'Operações',
    description: 'KPIs, fila de envio e visão geral do negócio.',
    icon: 'layout-dashboard',
    group: 'operacao',
  },
  {
    href: '/admin/notificacoes',
    label: 'Notificações',
    eyebrow: 'Alertas',
    description: 'Pedidos da loja, assinaturas e pagamentos em um só lugar.',
    icon: 'bell',
    group: 'operacao',
  },
  {
    href: '/admin/parceiros',
    label: 'Parceiros',
    eyebrow: 'Guilda',
    description: 'Assinaturas isentas de cobrança e gestão de parceiros.',
    icon: 'handshake',
    group: 'operacao',
  },
  {
    href: '/admin/clientes',
    label: 'Clientes',
    eyebrow: 'Guilda',
    description: 'Perfis, endereços e histórico por assinante.',
    icon: 'users',
    group: 'operacao',
  },
  {
    href: '/admin/assinaturas',
    label: 'Assinaturas',
    eyebrow: 'Recorrência',
    description: 'Status, gateways e sincronização de pagamentos.',
    icon: 'repeat',
    group: 'operacao',
  },
  {
    href: '/admin/ciclos',
    label: 'Produção',
    eyebrow: 'Fulfillment',
    description: 'Fila de caixas: aguardando, preparo, envio e entrega.',
    icon: 'package',
    group: 'operacao',
  },
  {
    href: '/admin/vendas',
    label: 'Vendas',
    eyebrow: 'Receita',
    description: 'Todas as vendas: assinaturas, loja avulsa e pedidos bundled.',
    icon: 'receipt',
    group: 'operacao',
  },
  {
    href: '/admin/financeiro',
    label: 'Financeiro',
    eyebrow: 'Fluxo de caixa',
    description: 'Entradas de pedidos, gastos operacionais e saldo líquido.',
    icon: 'landmark',
    group: 'operacao',
    children: [
      { href: '/admin/financeiro', label: 'Fluxo' },
      { href: '/admin/financeiro/gastos', label: 'Gastos' },
      { href: '/admin/financeiro/gateway', label: 'Gateway' },
      { href: '/admin/financeiro/assinantes', label: 'Assinantes' },
      { href: '/admin/pagamentos', label: 'Pagamentos' },
    ],
  },
  {
    href: '/admin/planos',
    label: 'Planos',
    eyebrow: 'Catálogo',
    description: 'Preços, frete e flags comerciais dos planos.',
    icon: 'layers',
    group: 'catalogo',
  },
  {
    href: '/admin/loja',
    label: 'Loja',
    eyebrow: 'Catálogo',
    description: 'Produtos, categorias e banners da vitrine.',
    icon: 'shopping-bag',
    group: 'catalogo',
    children: [
      { href: '/admin/loja', label: 'Produtos' },
      { href: '/admin/loja/pedidos', label: 'Pedidos' },
      { href: '/admin/loja/categorias', label: 'Categorias' },
      { href: '/admin/loja/banners', label: 'Banners' },
    ],
  },
  {
    href: '/admin/temas',
    label: 'Temas',
    eyebrow: 'Lore',
    description: 'Temas mensais, reveal e arte das caixas.',
    icon: 'palette',
    group: 'catalogo',
  },
  {
    href: '/admin/cupons',
    label: 'Cupons',
    eyebrow: 'Promo',
    description: 'Códigos de desconto para checkout.',
    icon: 'ticket',
    group: 'catalogo',
  },
  {
    href: '/admin/marketing',
    label: 'Marketing',
    eyebrow: 'Comunicação',
    description: 'Campanhas por e-mail para a base via Resend.',
    icon: 'mail',
    group: 'comunicacao',
    children: [
      { href: '/admin/marketing', label: 'Enviar campanha' },
      { href: '/admin/marketing/leads', label: 'Leads', showCount: true },
      { href: '/admin/marketing/historico', label: 'Histórico de disparos' },
    ],
  },
  {
    href: '/admin/feedbacks',
    label: 'Feedbacks',
    eyebrow: 'Clientes',
    description: 'Avaliações pós-entrega com nota, comentários e fotos.',
    icon: 'star',
    group: 'comunicacao',
  },
  {
    href: '/admin/ferramentas/qr',
    label: 'QR Code',
    eyebrow: 'Comunicação',
    description: 'Gere QR Codes do site para material publicitário.',
    icon: 'qr-code',
    group: 'comunicacao',
  },
  {
    href: '/admin/auditoria',
    label: 'Auditoria',
    eyebrow: 'Trilha',
    description: 'Histórico de ações administrativas.',
    icon: 'scroll-text',
    group: 'sistema',
  },
] as const;

export const ADMIN_NAV_GROUPS = [
  { id: 'operacao' as const, label: 'Operação' },
  { id: 'catalogo' as const, label: 'Catálogo' },
  { id: 'comunicacao' as const, label: 'Comunicação' },
  { id: 'sistema' as const, label: 'Sistema' },
] as const;
