export const ADMIN_NAV = [
  {
    href: '/admin',
    label: 'Dashboard',
    eyebrow: 'Operações',
    description: 'KPIs, fila de envio e visão geral do negócio.',
    icon: 'layout-dashboard',
    group: 'operacao',
  },
  {
    href: '/admin/parceiros',
    label: 'Parceiros',
    eyebrow: 'Guilda',
    description: 'Assinaturas isentas de cobrança e gestão de parceiros.',
    icon: 'handshake',
    group: 'operacao',
  },
  {
    href: '/admin/clientes',
    label: 'Clientes',
    eyebrow: 'Guilda',
    description: 'Perfis, endereços e histórico por assinante.',
    icon: 'users',
    group: 'operacao',
  },
  {
    href: '/admin/assinaturas',
    label: 'Assinaturas',
    eyebrow: 'Recorrência',
    description: 'Status, gateways e sincronização de pagamentos.',
    icon: 'repeat',
    group: 'operacao',
  },
  {
    href: '/admin/ciclos',
    label: 'Produção',
    eyebrow: 'Fulfillment',
    description: 'Fila de caixas: aguardando, preparo, envio e entrega.',
    icon: 'package',
    group: 'operacao',
  },
  {
    href: '/admin/vendas',
    label: 'Vendas',
    eyebrow: 'Receita',
    description: 'Todas as vendas: assinaturas, loja avulsa e pedidos bundled.',
    icon: 'receipt',
    group: 'operacao',
  },
  {
    href: '/admin/pagamentos',
    label: 'Pagamentos',
    eyebrow: 'Cofre',
    description: 'Histórico de cobranças aprovadas e pendentes.',
    icon: 'wallet',
    group: 'operacao',
  },
  {
    href: '/admin/planos',
    label: 'Planos',
    eyebrow: 'Catálogo',
    description: 'Preços, frete e flags comerciais dos planos.',
    icon: 'layers',
    group: 'catalogo',
  },
  {
    href: '/admin/temas',
    label: 'Temas',
    eyebrow: 'Lore',
    description: 'Temas mensais, reveal e arte das caixas.',
    icon: 'palette',
    group: 'catalogo',
  },
  {
    href: '/admin/cupons',
    label: 'Cupons',
    eyebrow: 'Promo',
    description: 'Códigos de desconto para checkout.',
    icon: 'ticket',
    group: 'catalogo',
  },
  {
    href: '/admin/marketing',
    label: 'Marketing',
    eyebrow: 'Comunicação',
    description: 'Campanhas por e-mail para a base via Resend.',
    icon: 'mail',
    group: 'comunicacao',
  },
  {
    href: '/admin/auditoria',
    label: 'Auditoria',
    eyebrow: 'Trilha',
    description: 'Histórico de ações administrativas.',
    icon: 'scroll-text',
    group: 'sistema',
  },
] as const;

export const ADMIN_NAV_GROUPS = [
  { id: 'operacao' as const, label: 'Operação' },
  { id: 'catalogo' as const, label: 'Catálogo' },
  { id: 'comunicacao' as const, label: 'Comunicação' },
  { id: 'sistema' as const, label: 'Sistema' },
] as const;
